MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/data3/XT/pretrain/resnet50-19c8e357.pth'
  CENTER_LOSS: 'on'
  CENTER_FEAT_DIM: 2048
  NAME: 'resent_nl_twoline_rgbd_rgb'
  WEIGHT_REGULARIZED_TRIPLET: 'on'
  GENERALIZED_MEAN_POOL: 'on'
  USEOWN_TRANSFORM : 'on'
INPUT:
  RGB:
    SIZE_TRAIN: [ 256, 128 ]
    SIZE_TEST: [ 256, 128 ]
    PROB: 0.5 # random horizontal flip
    RE_PROB: 0.5 # random erasing
    PADDING: 10
    PIXEL_MEAN: [
      0.485, 0.456, 0.406 ]
    PIXEL_STD: [ 0.229, 0.224, 0.225 ]
  DEPTH:
    SIZE_TRAIN: [256, 128]
    SIZE_TEST: [256, 128]
    PROB: 0.5 # random horizontal flip
    RE_PROB: 0.5 # random erasing
    PADDING: 10
    PIXEL_MEAN: [0.5]
    PIXEL_STD: [0.5]
  IMG_SIZE: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('tvpr2')
  ROOT_DIR : ('/data3/QK/REID')

DATALOADER:
  PK_SAMPLER: 'on'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'off'
  WEIGHT: "path"
  FEAT_NORM: 'on'
  EVALUATE_ONLY: 'off'
  PARTIAL_REID: 'off'

OUTPUT_DIR: "./log/tvpr2_T/AGW_baseline_twoline_rgbd_rgb_conv"
#这个配置用来直接输入rgb和rgbd放一起融合的过程，使用自己修正过的transform，看下会不会比之前的好


